GET https://directus-production-9585.up.railway.app/items/profile
content-type: application/json

#####
POST http://localhost:5000/api/auth/
content-type: application/json

{
    "pseudonym":"raoakif",
    "password":"123456"
}

###
GET https://writing-hat-api.vercel.app/api/prompts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MzE0OTgxMCwiZXhwIjoxNjgzNzU0NjEwfQ.UA9dn0AfjGqZnTDo8wUpaTiGcdpa6qGMYNHCQuCOISU

###
GET https://writing-hat-api.vercel.app/api/responses
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MzE0OTgxMCwiZXhwIjoxNjgzNzU0NjEwfQ.UA9dn0AfjGqZnTDo8wUpaTiGcdpa6qGMYNHCQuCOISU



###
PUT https://writing-hat-api.vercel.app/api/prompts/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MzE0OTgxMCwiZXhwIjoxNjgzNzU0NjEwfQ.UA9dn0AfjGqZnTDo8wUpaTiGcdpa6qGMYNHCQuCOISU

{
  "title": "No Nonsense",
  "description": "Finally someone showed up with a glass of water! They always wondered if the ghost had finally  dissappeared from the house. No other sounds were ever heard from the dusty basement anymore. They always would wonder if the ghost had finally left and dissappeared from the house.They always  wondered if the ghost had finally  dissappeared from the house. They always  wondered if the ghost had finally  dissappeared from the house. I They always  wondered if the ghost had finally  dissappeared from the house.",
  "promptCategoryId": 1,
  "userId": 1
}

{
  "title": "Sleep Hollow",
  "description": "No other sounds were ever heard from the basement anymore. They always wondered if the ghost had finally  dissappeared from the house. No other sounds were ever heard from the dusty basement anymore. They always would wonder if the ghost had finally left and dissappeared from the house.They always  wondered if the ghost had finally  dissappeared from the house. They always  wondered if the ghost had finally  dissappeared from the house. I They always  wondered if the ghost had finally  dissappeared from the house.",
  "promptId": 2,
  "userId": 1
}

# {
#   "title": "Sleep Hollow",
#   "description": "No other sounds were ever heard from the basement anymore. They always wondered if no other sounds were ever heard from the basement anymore.",
#   "userId": 1,
#   "promptId": 1
# }

###
GET https://writing-hat-api.vercel.app/api/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MzE0OTgxMCwiZXhwIjoxNjgzNzU0NjEwfQ.UA9dn0AfjGqZnTDo8wUpaTiGcdpa6qGMYNHCQuCOISU


### REGISTER A USER
POST https://writing-hat-api.vercel.app/api/users
Content-Type: application/json

{
  "pseudonym": "raoakif08",
  "email": "akifrao8@gmail.com",
  "city": "Lahore",
  "country": "Pakistan",
  "password": "123456",
  "profileImage": "https://avatars.githubusercontent.com/u/61361037?s=400&u=5a3fe223b969f16e2a4523817eb3acf361935f74&v=4"
}